### PR TITLE
Prerelease Version 1.2

### PR DESCRIPTION
**Pull request by thomafe**
### What's the reason for this pull request?

Added the following features
* Further improved user experience
* Added a main menu
* Added a level using all features from v1.1 continuing the story from part 1
* Cleaned up the code
* Added the "go back" command
* Added intros and endings
* Fixed a lot of bugs

This is a prerelase for version 1.2

### What things may need reviewing?

The game was tested thoroughly but there might still be some bugs left. All developers should test (with the new and old game).
After local testing more bugs may be found after the coming release.

### After resolving conflicts and reviews, should this be merged right away?

Yes, the version will be tagged later.

### CODE REVIEW

**Comment by simone273** [comment]
Nullpointer exception at choosing level when spelling the name of the level wrong

**Comment by 2Who** [comment]
> Nullpointer exception at choosing level when spelling the name of the level wrong

Fixed the issue

**Comment by simone273** [comment]
When you can't pick up something that is in the room, it says there is no such item but there is you just can't take it

**Review by lehmeti — APPROVED** [review]

**Comment by simone273** [comment]
exception when you do look at something and then spell the thing you want to look at wrong

**Comment by simone273** [comment]
We should rename level 'part of the crew...' to 'part of the crew'

**Comment by simone273** [comment]
Nullpointer Exception at 'Do you want to use an item or do you want to leave?' - 'leave'

**Comment by simone273** [comment]
Describe in introduction how the game works. For example that you can  not only go to passages or places but also to furnitures

**Comment by thomafe** [comment]
> 
> 
> Describe in introduction how the game works. For example that you can not only go to passages or places but also to furnitures

Will be done in next version.

**Comment by thomafe** [comment]
> 
> 
> Nullpointer Exception at 'Do you want to use an item or do you want to leave?' - 'leave'

Fixed.

**Review by simone273 — APPROVED** [review]

**Review by 2Who — APPROVED** [review]
Passt schon

**Pull request merged**
